### ISSUE TITLE
[Bug] Unable to install packages from Bioconductor

### ISSUE THREAD

**Issue by kpadm** [ankane/jetpack#3] opened 2018-08-17 16:27 UTC
Hello,

I am unable to install any package from Bioconductor using the format of the remotes argument given in the help section. For example, see below:

`> jetpack::add("SummarizedExperiment", remotes="bioc::3.7/SummarizedExperiment, bioc::release/Biobase")
svn: E175013: Unable to connect to a repository at URL 'https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_7/madman/Rpacks/SummarizedExperiment'
svn: E175013: Access to 'https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_7/madman/Rpacks/SummarizedExperiment' forbidden
Error: There was a problem retrieving the current SVN revision
In addition: Warning message:
In system2(svn_binary_path, paste("info --xml", url), stdout = TRUE) :
  running command ''/usr/bin/svn' info --xml --username readonly --password readonly https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_7/madman/Rpacks/SummarizedExperiment' had status 1
Error in unloadNamespace(pkgName) :
  namespace ‘httr’ is imported by ‘biomaRt’ so cannot be unloaded
In addition: Warning message:
‘httr’ namespace cannot be unloaded:
  namespace ‘httr’ is imported by ‘biomaRt’ so cannot be unloaded
Error in unloadNamespace(pkgName) :
  namespace ‘withr’ is imported by ‘pkgmaker’ so cannot be unloaded
In addition: Warning message:
‘withr’ namespace cannot be unloaded:
  namespace ‘withr’ is imported by ‘pkgmaker’ so cannot be unloaded
`
Please help me figure out what I am doing wrong. Thanks. 

Regards,

Karthik

**Comment by ankane** [comment] 2018-08-17 19:35
Hey @kpadm, thanks for reporting 👍 It looks like that remote scheme only works with earlier versions of Bioconductor. You should be able to do:

```r
jetpack::add("SummarizedExperiment", remotes="bioc::SummarizedExperiment")
```

Unfortunately, it then fails to download the package source when snapshotting. I'm able to reproduce with Packrat, but haven't found a fix.

```r
packrat::init()
source("https://bioconductor.org/biocLite.R")
packrat::extlib(c("withr", "devtools"))
devtools::install_bioc("Biobase")
packrat::snapshot()
```

**Comment by ankane** [comment] 2018-08-17 20:14
Installation should be fixed on master. Install the latest version with:

```r
devtools::install_github("ankane/jetpack")
```

And install packages with:

```r
jetpack::add("SummarizedExperiment", remotes="bioc::SummarizedExperiment")
```

However, looks like there are still issues when other collaborators try to do `jetpack::install()`, so going to leave this open until that is addressed.

**Comment by ankane** [comment] 2018-08-17 22:43
It looks like downloads are failing due to an issue with the Bioconductor archive. I notified [the Bioconductor team](https://support.bioconductor.org/p/112197/). If this is addressed, just need to merge a small change from the `bioconductor` branch and everything should work.

**Comment by kpadm** [comment] 2018-08-18 01:50
Thanks Andrew, I installed the latest version and am now able to install packages from `Bioconductor`.

**Closed** 2018-10-30 21:35 UTC
Labels: waiting
